# Generated by Django 5.1.7 on 2025-03-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
