# Generated by Django 5.1.7 on 2025-03-31 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_categories_emergencyrequest_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.categories'),
        ),
    ]
