# Generated by Django 5.2 on 2025-04-09 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0006_blogpost_blogpostimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='poster',
            new_name='author',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
